---

- name: Remove packages
  yum:
    name:
      - qemu-kvm
      - libvirt
    state: absent

- name: Remove test directory
  file:
    path: "{{ kvm_test_dir }}"
    state: absent

- name: Remove qemu-kvm symlink
  file:
    path: /usr/bin/qemu-kvm
    state: absent
