---

- name: Make test directory
  file:
    path: "{{ kvm_test_dir }}"
    state: directory

- name: Copy files
  copy: src=kvm/ dest="{{ kvm_test_dir }}/" mode=0755

- name: Check kvm compatibility
  shell: "{{ kvm_test_dir }}/pre-checks.sh"
  register: kvm_compatibility

- name: Write logs
  become: no
  local_action: copy content="{{ kvm_compatibility.stdout }}" dest="logs/kvm_compatibility.log"

- name: Install qemu
  when: kvm_compatibility.rc == 0
  block:
    - name: Install packages
      yum:
        name:
          - qemu-kvm
          - libvirt
        state: present
    - name: Restart libvirtd service
      systemd:
        name: libvirtd.service
        state: restarted
    - name: Check qemu installation
      shell: "{{ kvm_test_dir }}/qemu-installation-checks.sh"
      register: qemu_is_ok
    - name: Write logs
      become: no
      local_action: copy content="{{ kvm_compatibility.stdout }}\n{{ qemu_is_ok.stdout }}" dest="logs/kvm_compatibility.log"
    - name: Create qemu-kvm symlink # for `virsh create`
      file:
        src: /usr/libexec/qemu-kvm
        dest: /usr/bin/qemu-kvm
        state: link
        owner: root
        group: root
