---

- name: Hardware certification
  hosts: all
  vars_files:
    - vars.yml
  ignore_errors: true
  environment:
    LANG: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"
  tasks:

    # GENERAL SETUP
    - name: Create logs dir
      tags: [logs_folder, containers, cpu, hw_detection, kvm, network, raid, ltp, phoronix, cllimits]
      block:
        - name: Create logs dir
          ansible.builtin.file:
            path: "{{ lts_logs_dir }}"
            state: "directory"
            mode: "0755"
          delegate_to: localhost

    - name: Copy tests
      tags: [tests_copy, containers, cpu, hw_detection, kvm, network, raid, ltp, phoronix, cllimits]
      block:
        - name: Copy tests
          ansible.builtin.copy:
            src: "{{ lts_tests_dir }}/"
            dest: "{{ sut_tests_dir }}"
            mode: "0777"

    ##########

    # EXAMPLE
    # - tags: example
    #   block:
    #   - include: "{{ lts_tests_dir }}/example/roles/main.yml"

    # CONTAINERS
    - name: Containers
      tags: containers
      block:
        - name: Containers
          ansible.builtin.include_tasks: "{{ lts_tests_dir }}/containers/roles/main.yml"

    # CPU
    - name: CPU
      tags: cpu
      block:
        - name: CPU
          ansible.builtin.include_tasks: "{{ lts_tests_dir }}/cpu/roles/main.yml"

    # HW DETECTION
    - name: Hardware Detection
      tags: hw_detection
      block:
        - name: Hardware Detection
          ansible.builtin.include_tasks: "{{ lts_tests_dir }}/hw_detection/roles/main.yml"

    # KVM
    - name: KVM
      tags: kvm
      become: true
      block:
        - name: KVM
          ansible.builtin.include_tasks: "{{ lts_tests_dir }}/kvm/roles/main.yml"

    # NETWORK
    - name: Network
      tags: network
      block:
        - name: Network
          ansible.builtin.include_tasks: "{{ lts_tests_dir }}/network/roles/main.yml"

    # RAID
    - name: MD RAID
      tags: raid
      block:
        - name: MD RAID
          ansible.builtin.include_tasks: "{{ lts_tests_dir }}/raid/roles/main.yml"

    # LTP
    - name: LTP
      tags: ['never', 'ltp']
      block:
        - name: LTP
          ansible.builtin.include_tasks: "{{ lts_tests_dir }}/ltp/roles/main.yml"

    # PHORONIX
    - name: Phoronix
      tags: ['never', 'phoronix']
      block:
        - name: Phoronix
          ansible.builtin.include_tasks: "{{ lts_tests_dir }}/phoronix/roles/main.yml"

    # lve limits/cagefs
    - name: CL limits
      tags: cllimits
      when: ansible_distribution != 'AlmaLinux'
      block:
        - name: CL limits
          ansible.builtin.include_tasks: "{{ lts_tests_dir }}/cllimits/roles/main.yml"

    ##########

    # GENERAL CLEANUP
    - name: Cleanup
      tags: [tests_cleanup, containers, cpu, hw_detection, kvm, network, raid, ltp, phoronix, cllimits]
      block:
        - name: Remove tests
          ansible.builtin.file:
            path: "{{ sut_tests_dir }}"
            state: absent
