---

- name: Hardware certification
  hosts: all
  vars_files:
    - vars.yml
  ignore_errors: true
  environment:
    LANG: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"
  tasks:

    #GENERAL SETUP
    - tags: [logs_folder, containers, cpu, hw_detection, kvm, network, raid, ltp, phoronix, cllimits]
      block:
        - name: Create logs dir
          local_action: file path="{{ lts_logs_dir }}" state="directory" mode="0755"

    - tags: [tests_copy, containers, cpu, hw_detection, kvm, network, raid, ltp, phoronix, cllimits]
      block:
        - name: Copy tests
          copy:
            src: "{{ lts_tests_dir }}/"
            dest: "{{ sut_tests_dir }}"
            mode: 0777

    ##########

    #EXAMPLE
    #- tags: example
    #  block:
    #  - include: "{{ lts_tests_dir }}/example/roles/main.yml"

    #CONTAINERS
    - tags: containers
      block:
        - include: "{{ lts_tests_dir }}/containers/roles/main.yml"

    #CPU
    - tags: cpu
      block:
        - include: "{{ lts_tests_dir }}/cpu/roles/main.yml"

    #HW DETECTION
    - tags: hw_detection
      block:
        - include: "{{ lts_tests_dir }}/hw_detection/roles/main.yml"

    #KVM
    - tags: kvm
      become: yes
      block:
        - include: "{{ lts_tests_dir }}/kvm/roles/main.yml"

    #NETWORK
    - tags: network
      block:
        - include: "{{ lts_tests_dir }}/network/roles/main.yml"

    #RAID
    - tags: raid
      block:
        - include: "{{ lts_tests_dir }}/raid/roles/main.yml"

    #LTP
    - tags: [ 'never', 'ltp']
      block:
        - include: "{{ lts_tests_dir }}/ltp/roles/main.yml"

    #PHORONIX
    - tags: [ 'never', 'phoronix' ]
      block:
        - include: "{{ lts_tests_dir }}/phoronix/roles/main.yml"

    #lve limits/cagefs
    - tags: cllimits
      block:
        - include: "{{ lts_tests_dir }}/cllimits/roles/main.yml"
      when: ansible_distribution != 'AlmaLinux'

    ##########

    #GENERAL CLEANUP
    - tags: [tests_cleanup, containers, cpu, hw_detection, kvm, network, raid, ltp, phoronix, cllimits]
      block:
        - name: Remove tests
          file:
            path: "{{ sut_tests_dir }}"
            state: absent