---

- name: Test
  hosts: all
  vars_files:
    - vars.yml
  ignore_errors: true
  tasks:
    #GENERAL
    - name: Find logs
      local_action: find paths=logs patterns="*.log"
      register: find_logs
      tags: logs_cleanup
    - name: Cleanup logs
      local_action: file path="{{ item['path'] }}" state=absent
      with_items: "{{ find_logs['files'] }}"
      tags: logs_cleanup
    #CPU
    - include: cpu/roles/setup.yml
    - include: cpu/roles/test.yml
    - include: cpu/roles/cleanup.yml
    #NETWORK
    - include: network/roles/setup.yml
    - include: network/roles/test.yml
    - include: network/roles/cleanup.yml
    #RAID
    - include: raid/roles/setup.yml
    - include: raid/roles/test.yml
    - include: raid/roles/cleanup.yml
    #HW detection
    - name: Hardware detection
      tags: hw_detection
      block:
      - include: hw_detection/roles/setup.yml
      - include: hw_detection/roles/test.yml
      - include: hw_detection/roles/cleanup.yml
    #EXAMPLE
    #- include: example/roles/setup.yml
    #- include: example/roles/test.yml
    #- include: example/roles/cleanup.yml
