---

- name: Test CPU install utilities
  yum:
    name: stress-ng
    state: latest
    enablerepo: epel
  tags: test_cpu

- name: Test CPU copy script
  copy: src=cpu/run_test.sh dest=/root mode=0777
  tags: test_cpu
