---

- name: Raid test. Install dependent software
  yum:
    name:
      - mdadm
      - fio
  tags: test_raid

- name: Raid test copy script
  copy: src=raid/run_test.sh dest=/root mode=0777
  tags: test_raid